[defaults]
format = "{time}"

[[sessions]]
id = "work"
name = "Work"
duration = "25m"
command = "notify 'Work Done!'"

[[sessions]]
id = "rest"
name = "Rest"
duration = "5m"
command = "notify 'Rest Done!'"
