[defaults]
format = "{time}"
time_format = "%*H:%M:%S"

[[sessions]]
id = "work"
name = "Work"
duration = "40m"
command = "notify 'Work Done!'"

[[sessions]]
id = "rest"
name = "Rest"
duration = "10m"
command = "notify 'Rest Done!'"
