# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  flake.modules.nixos.praesidium =
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:

    {
      imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

      boot.initrd.availableKernelModules = [
        "xhci_pci"
        "ehci_pci" # USB 2.0 ports, often the only ones that work in a pinch
        "ahci"
        "nvme"
        "usbhid"
        "hid_generic"
      ];

      # Force-loaded, not merely available: `availableKernelModules` only loads
      # on a udev match, and a stage-1 emergency shell must always have a
      # keyboard. usbhid is the transport, hid_generic binds it as an input.
      boot.initrd.kernelModules = [
        "usbhid"
        "hid_generic"
      ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];

      # This firmware advertises an ACPI Time & Alarm Device, so the kernel
      # gives it rtc0 and demotes rtc_cmos. acpi_tad implements no RTC ioctls,
      # so /dev/rtc is unreadable and save-hwclock fails on every shutdown.
      boot.blacklistedKernelModules = [ "acpi_tad" ];

      # disko generates every `fileSystems.*` entry from this block. Addressed
      # by-id, since `disko --mode destroy` wipes whatever it is pointed at and
      # kernel device names can shift.
      disko.devices.disk.main = {
        type = "disk";
        device = "/dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S6S1NS0W210475Z";
        content = {
          type = "gpt";
          partitions = {
            ESP = {
              size = "512M";
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                # The default vfat masks make /boot world-readable, leaking the
                # systemd-boot random-seed file. Nothing needs it non-root.
                mountOptions = [
                  "fmask=0077"
                  "dmask=0077"
                ];
              };
            };
            root = {
              size = "100%";
              content = {
                type = "btrfs";
                extraArgs = [
                  "-L"
                  "nixos"
                ];
                subvolumes = {
                  "@" = {
                    mountpoint = "/";
                    mountOptions = [
                      "compress=zstd:3"
                      "noatime"
                    ];
                  };
                  "@home" = {
                    mountpoint = "/home";
                    mountOptions = [
                      "compress=zstd:3"
                      "noatime"
                    ];
                  };
                  "@nix" = {
                    mountpoint = "/nix";
                    mountOptions = [
                      "compress=zstd:3"
                      "noatime"
                    ];
                  };
                  "@var" = {
                    mountpoint = "/var";
                    mountOptions = [
                      "compress=zstd:3"
                      "noatime"
                    ];
                  };
                  # Reserved for impermanence; mounted now so adopting it later
                  # needs no second data shuffle.
                  "@persist" = {
                    mountpoint = "/persist";
                    mountOptions = [
                      "compress=zstd:3"
                      "noatime"
                    ];
                  };
                  "@snapshots" = {
                    mountpoint = "/.snapshots";
                    mountOptions = [ "noatime" ];
                  };
                  # No compression: swap needs stable, fully-allocated extents.
                  # Its own subvolume because a subvolume holding an active
                  # swapfile cannot be snapshotted.
                  "@swap" = {
                    mountpoint = "/swap";
                    mountOptions = [ "noatime" ];
                  };
                };
              };
            };
          };
        };
      };

      # NixOS creates this itself; on btrfs its mkswap unit uses
      # `btrfs filesystem mkswapfile`, so no manual `chattr +C` is needed.
      swapDevices = [
        {
          device = "/swap/swapfile";
          size = 8 * 1024;
        }
      ];

      boot.supportedFilesystems = [ "btrfs" ];
      environment.systemPackages = [ pkgs.btrfs-progs ];

      zramSwap = {
        enable = true;
        memoryPercent = 50;
      };

      # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
      # (the default) this is the recommended approach. When using systemd-networkd it's
      # still possible to use this option, but it's recommended to use it in conjunction
      # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
      networking.useDHCP = lib.mkDefault true;
      # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
      # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

      powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
