api_key: ENC[AES256_GCM,data:uB2o13vUexTMs8WJKIBVecGDdeUdFCE7MBUGtVE0yus6FDnga4T711jyTZ8=,iv:QD5fdl+ZGUJAmyRtk9G4XXdHvHqVTQ1VZoJ05cZmV2k=,tag:/+zNhgqucSDvT4LXzzyS6w==,type:str]
ota_password: ENC[AES256_GCM,data:GdOOHZi5xxduUFVAEH/DonimH1X4OqRQF9JIC0pOe60=,iv:+mrkEECMtf6JbzSYyBhS0OAQpQ62RIkCVQ6rS6tJaJA=,tag:uX/ypxE6ALLDOth2F6mxRA==,type:str]
ap_password: ENC[AES256_GCM,data:FubceC1WyC0yCr/MVsqaJg==,iv:cho9rpuJYE6qPCrazvF+WStjK8F7bvnjPAIbhUGCFJQ=,tag:/rJ/yxabjh+05raifMX5Gw==,type:str]
sops:
    age:
        - recipient: age17muvhm5l3khzd2n5m64rge329n672sg20jad0u58rugvtwswhp6s6dfmd3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUG13NFNrTGh1YnVDdE8x
            UnNIc3ZtLzdsenlJV0dHR3JOazVaZ0YrZEJJCjZXbU80bnZaR0l6cy9wejE4Ynl0
            MlNUeXRqNTkraEJmZEd2dXRHcDUvU1UKLS0tIElxaVRmeHFKazVMdTRta3Yyd0pP
            OTJJMGlqK1d3ZHEyMlVMUHc2bGF2V00KCVloFfCgxKAR/30JE9wzZgBavAs8hXI8
            neSorF8kETf5M4R7njlbJLIvN3qWtzLGFnhLeRNVRAhLTdpjrjmVRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T06:47:13Z"
    mac: ENC[AES256_GCM,data:Yq83W/2LIhL76ZrgOG2q/Ky7wUXWnfRXNoehxTcjdtMgduk3kLBXhKGncCtgHzoAmKUY7bkRpZJw4T9GZXsI0lQ2kdMtf97gKWxiMD7gEXyc3PH6Ejqsb1OGv9yzk8e689FTSNCUfuj/hFce5TejYPdwAYw4EWQuuvR7E29o7Hs=,iv:UirNBcblG3yu5NmYcs7kmYnsAIW/BZztR+dCF/ThOoQ=,tag:F4QtrRs7E06Z0tithl2jYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
